version: "3"

services:
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile.prod
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEFAULT_THEME', 'no-theme');
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - wordpress-net

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.23.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - wordpress-vol:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - wordpress-net

networks:
  wordpress-net:
    driver: bridge

volumes:
  wordpress-vol:
