version: "3"

services:
  db:
    image: mariadb:10.11.13@sha256:e725b24af143c6b30e78eab99441e4cabac7494a69186effc2f506ea85401e2a
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
